@extends('layouts.site')
@section('title', 'รายการ #'.$order->id.' · 90th SISAT Reunion')
@section('content')<section class="page-hero"><div class="shell"><div class="eyebrow">Order #{{ $order->id }}</div><h1 class="page-title">{{ $order->kind === 'table' ? 'จองโต๊ะจีน + คอนเสิร์ต' : 'จองของที่ระลึก' }}</h1><span class="badge">{{ ['awaiting_slip'=>'รอส่งสลิป','pending_review'=>'รอตรวจสอบ','changes_requested'=>'กรุณาแก้ไขสลิป','approved'=>'อนุมัติแล้ว','redeemed'=>'ใช้สิทธิ์แล้ว','expired'=>'หมดเวลา','rejected'=>'ไม่ผ่านการตรวจ'][$order->status] ?? $order->status }}</span></div></section>
<section class="section" style="padding-top:16px"><div class="shell grid-2"><div class="panel"><h2>รายละเอียด</h2>@foreach($order->items as $item)<p>{{ $item->label }} × {{ $item->quantity }} <strong class="gold">฿{{ number_format($item->unit_price_satang * $item->quantity / 100) }}</strong></p>@endforeach<hr class="divider-line"><div class="price">รวม ฿{{ number_format($order->total_satang / 100) }}</div>@if($order->dietary_notes)<p class="help">แจ้งอาหาร: {{ $order->dietary_notes }}</p>@endif
@if($order->status === 'awaiting_slip' || $order->status === 'changes_requested')
<hr class="divider-line"><h3>ส่งหลักฐานการชำระเงิน</h3>@if($order->status === 'awaiting_slip')<p class="help">กรุณาส่งสลิปก่อน {{ $order->expires_at->timezone('Asia/Bangkok')->format('d/m/Y H:i') }}</p>@endif
@if(config('reunion.bank_account'))<p>โอนเข้าบัญชี {{ config('reunion.bank_name') }}<br><strong>{{ config('reunion.bank_account') }}</strong><br>{{ config('reunion.bank_holder') }}</p>@else<p class="help">โหมดสาธิต: ยังไม่มีบัญชีรับชำระเงินจริง กรุณาใช้ภาพตัวอย่างทดสอบการส่งสลิป</p>@endif
@if($order->finance_comment)<div class="error">เจ้าหน้าที่แจ้ง: {{ $order->finance_comment }}</div>@endif
<form class="form" method="post" enctype="multipart/form-data" action="{{ route('orders.slip', $order) }}">@csrf<div class="field"><label for="slip">ภาพสลิปหรือ PDF (ไม่เกิน 5 MB)</label><input class="input" id="slip" type="file" name="slip" accept="image/jpeg,image/png,image/webp,application/pdf" required></div><button class="btn" type="submit">ส่งสลิปให้ตรวจสอบ</button></form>
@elseif($order->status === 'pending_review')<p class="help">ได้รับสลิปแล้ว เจ้าหน้าที่การเงินกำลังตรวจสอบ</p>@elseif($order->status === 'expired')<p class="help">รายการหมดเวลาจอง กรุณาเลือกใหม่</p>@elseif($order->status === 'rejected')<div class="error">รายการไม่ผ่านการตรวจ: {{ $order->finance_comment }}</div>@endif
</div><div class="panel"><h2>สิทธิ์ของคุณ</h2>
@if($order->kind === 'table')<p class="muted">แต่ละ QR ใช้เข้างาน รับประทานอาหาร และชมคอนเสิร์ตได้ 1 คน สแกนแยกกันได้</p>@if($passes->isEmpty())<div class="empty">QR จะแสดงหลังเจ้าหน้าที่อนุมัติสลิป</div>@else<div class="stack">@foreach($passes as $pass)<div class="ticket"><strong>บัตรผ่านท่านที่ {{ $pass['number'] }}</strong><img src="{{ $pass['qr'] }}" alt="QR สำหรับผู้ร่วมโต๊ะท่านที่ {{ $pass['number'] }}"><small>{{ $pass['redeemed_at'] ? 'ใช้สิทธิ์แล้ว' : 'แสดง QR นี้ที่จุดเข้างาน' }}</small></div>@endforeach</div>@endif
@else @if($qr)<div class="ticket"><strong>QR รับของที่ระลึก</strong><img src="{{ $qr }}" alt="QR รับของที่ระลึก"><small>{{ $order->redeemed_at ? 'ใช้สิทธิ์แล้ว' : 'แสดง QR นี้ที่จุดรับของ' }}</small></div>@else<div class="empty">QR จะแสดงหลังเจ้าหน้าที่อนุมัติสลิป</div>@endif @endif
</div></div></section>@endsection
