@extends('layouts.site')
@section('title', 'ช่วยลูกค้า · 90th SISAT Reunion')
@section('content')<section class="page-hero"><div class="shell"><div class="eyebrow">Customer Assistance</div><h1 class="page-title">ทำรายการแทนลูกค้า</h1><p class="muted">ค้นหาบัญชีจากอีเมลหรือเบอร์โทร แล้วทำรายการในชื่อเจ้าของบัญชี ระบบบันทึกชื่อเจ้าหน้าที่ผู้ดำเนินการ</p></div></section>
<section class="section" style="padding-top:12px"><div class="shell stack"><div class="panel"><form class="form" method="get" action="{{ route('assist.index') }}"><div class="field"><label for="identifier">Email, phone, or Customer ID (e.g. #123)</label><input class="input" id="identifier" name="identifier" value="{{ $identifier }}" required></div><button class="btn" type="submit">ค้นหาลูกค้า</button></form></div>
@if($identifier && !$customer)<div class="empty">ไม่พบบัญชีนี้ กรุณาให้ลูกค้าสมัครด้วยอีเมลหรือเบอร์โทรก่อน</div>@endif
@if($customer)<div class="panel"><span class="badge">พบบัญชีลูกค้า</span><h2>{{ $customer->name }}</h2><p class="muted">{{ $customer->email ?: $customer->phone }}</p><div class="grid-2">
<form class="form" method="post" action="{{ route('assist.store') }}">@csrf<input type="hidden" name="customer_id" value="{{ $customer->id }}"><input type="hidden" name="kind" value="souvenir"><input type="hidden" name="client_key" value="{{ (string) Str::uuid() }}"><h3>จองของที่ระลึก</h3><div class="field"><label for="product">สินค้า</label><select class="input" name="resource_id" id="product">@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }} · ฿{{ number_format($product->price_satang / 100) }} · เหลือ {{ $product->available }}</option>@endforeach</select></div><div class="field"><label for="quantity">จำนวน</label><input class="input" type="number" id="quantity" name="quantity" value="1" min="1" max="10"></div><button class="btn" type="submit">สร้างรายการของที่ระลึก</button></form>
<div><h3>จองโต๊ะจีน + คอนเสิร์ต</h3><form method="get" action="{{ route('assist.index') }}" class="form"><input type="hidden" name="identifier" value="{{ $identifier }}"><div class="field"><label for="zone">โซนที่เปิดจอง</label><select class="input" id="zone" name="zone">@foreach($zones as $option)<option value="{{ $option->code }}" @selected($option->code === $zone?->code)>{{ $option->code }} · ฿{{ number_format($option->price_satang / 100) }}/โต๊ะ</option>@endforeach</select></div><button class="btn btn-ghost" type="submit">ดูโต๊ะว่าง</button></form>
@if($zone)<form class="form" method="post" action="{{ route('assist.store') }}" style="margin-top:14px">@csrf<input type="hidden" name="customer_id" value="{{ $customer->id }}"><input type="hidden" name="kind" value="table"><input type="hidden" name="quantity" value="1"><input type="hidden" name="client_key" value="{{ (string) Str::uuid() }}"><div class="field"><label for="resource_id">โต๊ะว่าง</label><select class="input" id="resource_id" name="resource_id">@foreach($tables as $table)<option value="{{ $table->id }}">{{ $table->zone }}{{ $table->label }} · {{ $table->capacity }} ท่าน</option>@endforeach</select></div><div class="field"><label for="dietary_notes">อาหารที่แพ้ / ไม่รับประทาน</label><textarea class="input" id="dietary_notes" name="dietary_notes" rows="2"></textarea></div><button class="btn" type="submit" @disabled($tables->isEmpty())>สร้างรายการโต๊ะจีน</button></form>@endif</div></div></div>@endif
<div class="panel"><h2>รายการที่คุณช่วยสร้างล่าสุด</h2><div class="order-list">@forelse($assistedOrders as $order)<a class="order-link" href="{{ route('orders.show', $order) }}">#{{ $order->id }} · {{ $order->kind === 'table' ? 'โต๊ะจีน' : 'ของที่ระลึก' }} <span class="badge">{{ $order->status }}</span></a>@empty<div class="empty">ยังไม่มีรายการ</div>@endforelse</div></div>
</div></section>@endsection
